In [64]:
import numpy as np
import pynq
from pynq import Overlay
import time

overlay = Overlay("/home/xilinx/jupyter_notebooks/test/pl_vecadd_pynq.bit")

vecadd_inst = overlay.pl_vecadd_0

In [65]:
array_a = pynq.allocate(shape=(1024,), dtype=np.float32)
array_b = pynq.allocate(shape=(1024,), dtype=np.float32)
array_c = pynq.allocate(shape=(1024,), dtype=np.float32)


for i in range(1024):
    array_a[i] = np.float32(i)
    array_b[i] = np.float32(i)
    array_c[i] = np.float32(-1.0)


array_a.sync_to_device()
array_b.sync_to_device()
array_c.sync_to_device()

array_a.physical_address

377860096

In [66]:
# help(vecadd_inst.mmio)
vecadd_inst.mmio.write_reg(0x10, array_a.physical_address)
vecadd_inst.mmio.write_reg(0x14, 0)
vecadd_inst.mmio.write_reg(0x1c, array_b.physical_address)
vecadd_inst.mmio.write_reg(0x20, 0)
vecadd_inst.mmio.write_reg(0x28, array_c.physical_address)
vecadd_inst.mmio.write_reg(0x2c, 0)

In [67]:

ip_status = vecadd_inst.read(0x00)
print(ip_status)


ip_status = vecadd_inst.read(0x00)
print(ip_status)

vecadd_inst.write(0x00, 1)
ip_status = vecadd_inst.read(0x00)
print(ip_status)
while (ip_status == 14):
    ip_status = vecadd_inst.read(0x00)
    
ip_status = vecadd_inst.read(0x00)
print(ip_status)
print('accelerator done')

4
4
14
4
accelerator done


In [68]:
ip_status = vecadd_inst.read(0x00)
print(ip_status)

array_a.sync_from_device()
array_b.sync_from_device()
array_c.sync_from_device()

print(array_a)
print(array_b)
print(array_c)


4
[0.000e+00 1.000e+00 2.000e+00 ... 1.021e+03 1.022e+03 1.023e+03]
[0.000e+00 1.000e+00 2.000e+00 ... 1.021e+03 1.022e+03 1.023e+03]
[0.000e+00 2.000e+00 4.000e+00 ... 2.042e+03 2.044e+03 2.046e+03]
